### PR TITLE
Add Exam Controller and Routes

### LINKED ISSUE #15: Exam Controller
**Problem**: We don't have routes set up for exams.
**Solution**:  Add controller/query methods and routes for exams.

**Specs:**
- [x] Complete methods in src/controller/ExamController.ts
- [x] Add routes to src/route/ExamRoutes.ts to match our old API

**Notes**
https://github.com/sandboxnu/pharmd-tracker-backend/blob/master/src/controllers/endpoints.md
https://github.com/sandboxnu/pharmd-tracker-backend/blob/master/src/controllers/assessmentsRoutes.js

If blocked, contact @someone

### PR DESCRIPTION
**Pull request by sophiacrennan**
Why does it show other peoples commits :(

### CODE REVIEW

**Review by emaela — APPROVED** [review]

**Comment by emaela** [comment]
> Why does it show other peoples commits :(

I think it's because the pull request's base branch was set to master, not typeorm - should be good now :)

**Review by emaela — DISMISSED** [review]
Looks good! I think we should remove console.log statements though, what do you think?

**Comment by Jose-S** [comment]
Yeah remove them, unless if you guys think they might be useful for debugging in the future

**Comment by emaela** [comment]
@sophiacrennan I'm getting some errors when running the backend - it might just be on my computer, do you think we could take a look at it together?

**Comment by sophiacrennan** [comment]
Removed `return response.send()` in the controller to get rid of the odd Buffer and Unhandled promise rejection errors. There is probably a better solution.

Querying by Id does not work yet...something to do with it being a uuid. @emaela did you run into this issue?

**Review by emaela — APPROVED** [review]
Sophie and I looked through this together, looks good to me

**Pull request merged**
